development:
  secret_key_base: dckB8lIQ5gvf_vb9z8kyPSfYu6IzsB6Fkew4ReAxYl0
  unsplash_api_key: 9SoHvRXOatpP6iSa0fNaHldL3_Ei7u6DoxGv0Saw5-w

test:
  # unsplash_api_key: fake-key
  secret_key_base: dckB8lIQ5gvf_vb9z8kyPSfYu6IzsB6Fkew4ReAxYl0
  unsplash_api_key: 9SoHvRXOatpP6iSa0fNaHldL3_Ei7u6DoxGv0Saw5-w